# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='checked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
