# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
