# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_rel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rel',
            name='count',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
